export enum ErrorCode {
  // Generic
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Posts
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  POST_UPDATE_FORBIDDEN = 'POST_UPDATE_FORBIDDEN',
  POST_DELETE_FORBIDDEN = 'POST_DELETE_FORBIDDEN',

  // Articles
  ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND',
  ARTICLE_SLUG_EXISTS = 'ARTICLE_SLUG_EXISTS',
  ARTICLE_UPDATE_FORBIDDEN = 'ARTICLE_UPDATE_FORBIDDEN',
  ARTICLE_DELETE_FORBIDDEN = 'ARTICLE_DELETE_FORBIDDEN',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_FOLLOWED = 'USER_ALREADY_FOLLOWED',
  USER_NOT_FOLLOWED = 'USER_NOT_FOLLOWED',
  PROFILE_UPDATE_FORBIDDEN = 'PROFILE_UPDATE_FORBIDDEN',
  CANNOT_FOLLOW_SELF = 'CANNOT_FOLLOW_SELF',

  // Comments
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  COMMENT_UPDATE_FORBIDDEN = 'COMMENT_UPDATE_FORBIDDEN',
  COMMENT_DELETE_FORBIDDEN = 'COMMENT_DELETE_FORBIDDEN',
  COMMENT_PARENT_INVALID = 'COMMENT_PARENT_INVALID',
  COMMENT_TARGET_INVALID = 'COMMENT_TARGET_INVALID',
  COMMENT_MENTION_NOT_ALLOWED = 'COMMENT_MENTION_NOT_ALLOWED',

  // Interactions
  ALREADY_LIKED = 'ALREADY_LIKED',
  NOT_LIKED = 'NOT_LIKED',
}
