export enum ErrorCode {
  // Generic
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',

  // Auth / email
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  EMAIL_VERIFICATION_TOKEN_INVALID = 'EMAIL_VERIFICATION_TOKEN_INVALID',
  EMAIL_VERIFICATION_TOKEN_EXPIRED = 'EMAIL_VERIFICATION_TOKEN_EXPIRED',
  PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID',
  PASSWORD_RESET_TOKEN_EXPIRED = 'PASSWORD_RESET_TOKEN_EXPIRED',

  // Posts
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  POST_UPDATE_FORBIDDEN = 'POST_UPDATE_FORBIDDEN',
  POST_DELETE_FORBIDDEN = 'POST_DELETE_FORBIDDEN',

  // Articles
  ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND',
  ARTICLE_SLUG_EXISTS = 'ARTICLE_SLUG_EXISTS',
  ARTICLE_UPDATE_FORBIDDEN = 'ARTICLE_UPDATE_FORBIDDEN',
  ARTICLE_DELETE_FORBIDDEN = 'ARTICLE_DELETE_FORBIDDEN',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_USERNAME_EXISTS = 'USER_USERNAME_EXISTS',
  USER_ALREADY_FOLLOWED = 'USER_ALREADY_FOLLOWED',
  USER_NOT_FOLLOWED = 'USER_NOT_FOLLOWED',
  PROFILE_UPDATE_FORBIDDEN = 'PROFILE_UPDATE_FORBIDDEN',
  CANNOT_FOLLOW_SELF = 'CANNOT_FOLLOW_SELF',

  // Comments
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  COMMENT_UPDATE_FORBIDDEN = 'COMMENT_UPDATE_FORBIDDEN',
  COMMENT_DELETE_FORBIDDEN = 'COMMENT_DELETE_FORBIDDEN',
  COMMENT_PARENT_INVALID = 'COMMENT_PARENT_INVALID',
  COMMENT_TARGET_INVALID = 'COMMENT_TARGET_INVALID',
  COMMENT_MENTION_NOT_ALLOWED = 'COMMENT_MENTION_NOT_ALLOWED',

  // Interactions
  ALREADY_LIKED = 'ALREADY_LIKED',
  NOT_LIKED = 'NOT_LIKED',

  // Notifications
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_UPDATE_FORBIDDEN = 'NOTIFICATION_UPDATE_FORBIDDEN',
  NOTIFICATION_STREAM_TOKEN_INVALID = 'NOTIFICATION_STREAM_TOKEN_INVALID',
  NOTIFICATION_STREAM_TOKEN_EXPIRED = 'NOTIFICATION_STREAM_TOKEN_EXPIRED',
}
