import { HttpStatus, Type, applyDecorators } from '@nestjs/common';
import {
  ApiBadRequestResponse,
  ApiConflictResponse,
  ApiCreatedResponse,
  ApiExtraModels,
  ApiForbiddenResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiResponse,
  ApiTooManyRequestsResponse,
  ApiUnauthorizedResponse,
  getSchemaPath,
} from '@nestjs/swagger';
import {
  ApiEnvelopeMetaDto,
  ApiEnvelopeWarningDto,
  ApiErrorResponseDto,
  PaginatedMetaDto,
  ValidationFieldErrorDto,
} from './swagger-response.dto';

type SwaggerType = Type<unknown>;

const buildEnvelopeSchema = (payloadSchema: Record<string, unknown>) => ({
  type: 'object',
  properties: {
    payload: payloadSchema,
    requestId: {
      type: 'string',
      description: 'Request identifier generated by the backend.',
      example: 'f95eeefc-71f3-4db2-8ad8-c8f4524f3431',
    },
    timestamp: {
      type: 'string',
      format: 'date-time',
      description: 'UTC timestamp when the response was generated.',
      example: '2026-02-15T21:10:35.120Z',
    },
    meta: {
      $ref: getSchemaPath(ApiEnvelopeMetaDto),
    },
    warnings: {
      type: 'array',
      items: { $ref: getSchemaPath(ApiEnvelopeWarningDto) },
    },
  },
  required: ['payload', 'requestId', 'timestamp'],
});

export function ApiEnvelopeOkResponse(
  payloadType: SwaggerType,
  description?: string,
) {
  return applyDecorators(
    ApiExtraModels(payloadType, ApiEnvelopeMetaDto, ApiEnvelopeWarningDto),
    ApiOkResponse({
      description,
      schema: buildEnvelopeSchema({ $ref: getSchemaPath(payloadType) }),
    }),
  );
}

export function ApiEnvelopeCreatedResponse(
  payloadType: SwaggerType,
  description?: string,
) {
  return applyDecorators(
    ApiExtraModels(payloadType, ApiEnvelopeMetaDto, ApiEnvelopeWarningDto),
    ApiCreatedResponse({
      description,
      schema: buildEnvelopeSchema({ $ref: getSchemaPath(payloadType) }),
    }),
  );
}

export function ApiEnvelopeArrayOkResponse(
  itemType: SwaggerType,
  description?: string,
) {
  return applyDecorators(
    ApiExtraModels(itemType, ApiEnvelopeMetaDto, ApiEnvelopeWarningDto),
    ApiOkResponse({
      description,
      schema: buildEnvelopeSchema({
        type: 'array',
        items: { $ref: getSchemaPath(itemType) },
      }),
    }),
  );
}

export function ApiEnvelopePaginatedOkResponse(
  itemType: SwaggerType,
  description?: string,
) {
  return applyDecorators(
    ApiExtraModels(
      itemType,
      ApiEnvelopeMetaDto,
      ApiEnvelopeWarningDto,
      PaginatedMetaDto,
    ),
    ApiOkResponse({
      description,
      schema: buildEnvelopeSchema({
        type: 'object',
        properties: {
          items: {
            type: 'array',
            items: { $ref: getSchemaPath(itemType) },
          },
          meta: { $ref: getSchemaPath(PaginatedMetaDto) },
        },
        required: ['items', 'meta'],
      }),
    }),
  );
}

export function ApiStandardErrorResponses() {
  return applyDecorators(
    ApiExtraModels(ApiErrorResponseDto, ValidationFieldErrorDto),
    ApiBadRequestResponse({
      type: ApiErrorResponseDto,
      description: 'Request validation or domain validation failed.',
    }),
    ApiUnauthorizedResponse({
      type: ApiErrorResponseDto,
      description: 'Authentication failed or missing credentials.',
    }),
    ApiForbiddenResponse({
      type: ApiErrorResponseDto,
      description: 'User is authenticated but not allowed to perform action.',
    }),
    ApiNotFoundResponse({
      type: ApiErrorResponseDto,
      description: 'Requested resource does not exist.',
    }),
    ApiConflictResponse({
      type: ApiErrorResponseDto,
      description: 'Resource state conflict.',
    }),
    ApiTooManyRequestsResponse({
      type: ApiErrorResponseDto,
      description: 'Rate limit exceeded.',
    }),
    ApiResponse({
      status: HttpStatus.INTERNAL_SERVER_ERROR,
      type: ApiErrorResponseDto,
      description: 'Unexpected server error.',
    }),
  );
}
